export const content = {
  brand: {
    name: 'LA MIA CASA',
    location: '[DA PERSONALIZZARE] Roma, Italia',
  },
  contacts: {
    whatsappDisplay: '+39 347 700 5683',
    whatsappUrl: 'https://wa.me/393477005683',
    phone: '[DA PERSONALIZZARE] +39 000 000 0000',
    email: '[DA PERSONALIZZARE] host@example.com',
    localEmergencyName: '[DA PERSONALIZZARE] Guardia medica locale',
    localEmergencyPhone: '[DA PERSONALIZZARE] +39 000 000 0000',
  },
  links: {
    propertyMap:
      'https://www.google.com/maps/search/?api=1&query=Via%20Tullio%20Ascarelli%2C%2099%20-%20Roma',
    review:
      'https://www.google.com/search?q=%5BDA%20PERSONALIZZARE%5D%20link%20recensione',
  },
  healthLinks: {
    openPharmacies:
      'https://www.federfarmaroma.com/farmacie_aperte.php',
    emergencyRooms: 'https://www.salutelazio.it/pronto-soccorso',
  },
  wifi: {
    network: '[DA PERSONALIZZARE] Nome rete Wi-Fi',
    password: '[DA PERSONALIZZARE] Password Wi-Fi',
  },
  locale: {
    it: {
      languageCode: 'it',
      languageName: 'Italiano',
      languageSelectorLabel: 'Lingua · Language',
      welcome:
        'Benvenuti. Qui trovate tutto ciò che serve per vivere la casa e la città con semplicità.',
      eyebrow: 'La vostra casa, a portata di mano',
      guidePrompt: 'Come possiamo aiutarvi?',
      openSection: 'Apri la sezione',
      close: 'Chiudi',
      maps: 'Apri in Google Maps',
      copyPassword: 'Copia password',
      copyPasswordSuccess: 'Accesso copiato',
      passwordCopied: 'Password copiata',
      copyFailed: 'Copia non riuscita: seleziona la password manualmente.',
      quickActionsLabel: 'Azioni rapide',
      quickActions: {
        whatsapp: 'WhatsApp host',
        recycling: 'Raccolta',
        emergency: 'Emergenze',
      },
      sections: [
        {
          id: 'checkin',
          title: 'Check-in',
          subtitle: 'Arrivo e accesso',
          addressLabel: 'Indirizzo',
          address: 'Via Tullio Ascarelli, 99 - Roma',
          checkInLabel: 'Check-in',
          checkIn: 'Ricordati di comunicare all’Host l’orario del tuo arrivo a casa.',
          housePhoto: '',
          housePhotoAlt: '[DA PERSONALIZZARE] Facciata di LA MIA CASA',
          housePhotoFallback: 'Foto della casa in arrivo',
          instructionsLabel: 'Come entrare',
          instructions:
            'All’arrivo troverai una persona che ti accoglierà e ti consegnerà le chiavi di casa.',
        },
        {
          id: 'wifi',
          title: 'Wi-Fi',
          subtitle: 'Rete e password',
          networkLabel: 'Nome rete',
          passwordLabel: 'Password',
          note: 'La rete è disponibile in tutta la casa.',
        },
        {
          id: 'rules',
          title: 'Regole casa',
          subtitle: 'Le cose essenziali',
          items: [
            {
              title: 'Clima',
              text: '[DA PERSONALIZZARE] Il comando dell’aria condizionata è vicino all’ingresso.',
            },
            {
              title: 'Elettrodomestici',
              text: '[DA PERSONALIZZARE] Cucina, forno, lavastoviglie e lavatrice sono a disposizione.',
            },
            {
              title: 'Raccolta differenziata',
              text: '[DA PERSONALIZZARE] I contenitori sono sotto il lavello; il calendario è sul frigorifero.',
            },
            {
              title: 'Silenzio',
              text: '[DA PERSONALIZZARE] Evitate rumori dalle 22:00 alle 08:00.',
            },
            {
              title: 'In casa',
              text: '[DA PERSONALIZZARE] Non è consentito fumare e non sono ammesse feste.',
            },
          ],
        },
        {
          id: 'food',
          title: 'Dove mangiare nei dintorni',
          subtitle: 'Sei indirizzi scelti per voi',
          places: [
            {
              name: '[DA PERSONALIZZARE] Trattoria del Vicolo',
              category: '[DA PERSONALIZZARE] Cucina romana',
              tip: '[DA PERSONALIZZARE] Ideale per una cena informale; provate il piatto del giorno.',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Trattoria%20del%20Vicolo',
            },
            {
              name: '[DA PERSONALIZZARE] Forno della Piazza',
              category: '[DA PERSONALIZZARE] Panificio',
              tip: '[DA PERSONALIZZARE] Perfetto per colazione e pizza al taglio.',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Forno%20della%20Piazza',
            },
            {
              name: '[DA PERSONALIZZARE] L’Oliva',
              category: '[DA PERSONALIZZARE] Vegetariano',
              tip: '[DA PERSONALIZZARE] Piatti stagionali e ottime opzioni senza glutine.',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20L%27Oliva',
            },
            {
              name: '[DA PERSONALIZZARE] Bottega 12',
              category: '[DA PERSONALIZZARE] Enoteca',
              tip: '[DA PERSONALIZZARE] Buona scelta per un aperitivo tranquillo.',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Bottega%2012',
            },
            {
              name: '[DA PERSONALIZZARE] Gelateria Fiore',
              category: '[DA PERSONALIZZARE] Gelateria',
              tip: '[DA PERSONALIZZARE] Gusti artigianali e sorbetti alla frutta.',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Gelateria%20Fiore',
            },
            {
              name: '[DA PERSONALIZZARE] Terrazza Verde',
              category: '[DA PERSONALIZZARE] Ristorante panoramico',
              tip: '[DA PERSONALIZZARE] Prenotate un tavolo esterno al tramonto.',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Terrazza%20Verde',
            },
          ],
        },
        {
          id: 'transport',
          title: 'Trasporti vicini',
          subtitle: 'Due linee sotto casa',
          stopLabel: 'Fermata sotto casa',
          directionLabel: 'Direzione',
          frequencyLabel: 'Passaggi',
          moovit: 'Apri in Moovit',
          lines: [
            {
              name: '[DA PERSONALIZZARE] Linea 01',
              color: '#a94e34',
              stop: '[DA PERSONALIZZARE] Fermata sotto casa',
              direction: '[DA PERSONALIZZARE] Centro / Stazione',
              frequency: '[DA PERSONALIZZARE] ogni 15–20 min',
              stops: [
                '[DA PERSONALIZZARE] Casa',
                '[DA PERSONALIZZARE] Piazza',
                '[DA PERSONALIZZARE] Metro',
                '[DA PERSONALIZZARE] Centro',
              ],
              moovit: 'https://moovitapp.com/rome-61/lines/it',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20fermata%20autobus',
            },
            {
              name: '[DA PERSONALIZZARE] Linea 02',
              color: '#65704a',
              stop: '[DA PERSONALIZZARE] Fermata sotto casa',
              direction: '[DA PERSONALIZZARE] Università / Ospedale',
              frequency: '[DA PERSONALIZZARE] ogni 20–25 min',
              stops: [
                '[DA PERSONALIZZARE] Casa',
                '[DA PERSONALIZZARE] Parco',
                '[DA PERSONALIZZARE] Università',
                '[DA PERSONALIZZARE] Ospedale',
              ],
              moovit: 'https://moovitapp.com/rome-61/lines/it',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20fermata%20autobus',
            },
          ],
        },
        {
          id: 'health',
          title: 'Farmacie e ospedali',
          subtitle: 'Assistenza nei dintorni',
          pharmaciesTab: 'Farmacie',
          hospitalsTab: 'Ospedali',
          tabsLabel: 'Scegli il tipo di assistenza',
          openPharmacies: 'Trova farmacie aperte',
          emergencyRooms: 'Trova pronto soccorso nel Lazio',
          emergencyNote:
            'In caso di emergenza chiama il 112: non scegliere un ospedale soltanto in base alla distanza.',
          phoneLabel: 'Telefono',
          pharmacies: [
            {
              name: '[DA PERSONALIZZARE] Farmacia 1',
              description: '[DA PERSONALIZZARE] Indirizzo e indicazioni',
              distance: '[DA PERSONALIZZARE] 3 min a piedi',
              phone: '[DA PERSONALIZZARE] +39 06 0000001',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20farmacia%201',
            },
            {
              name: '[DA PERSONALIZZARE] Farmacia 2',
              description: '[DA PERSONALIZZARE] Indirizzo e indicazioni',
              distance: '[DA PERSONALIZZARE] 7 min a piedi',
              phone: '[DA PERSONALIZZARE] +39 06 0000002',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20farmacia%202',
            },
            {
              name: '[DA PERSONALIZZARE] Farmacia 3',
              description: '[DA PERSONALIZZARE] Indirizzo e indicazioni',
              distance: '[DA PERSONALIZZARE] 10 min a piedi',
              phone: '[DA PERSONALIZZARE] +39 06 0000003',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20farmacia%203',
            },
          ],
          hospitals: [
            {
              name: '[DA PERSONALIZZARE] Ospedale 1',
              description: '[DA PERSONALIZZARE] Pronto soccorso e servizi principali',
              distance: '[DA PERSONALIZZARE] 4 km',
              phone: '[DA PERSONALIZZARE] +39 06 0000011',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20ospedale%201',
            },
            {
              name: '[DA PERSONALIZZARE] Ospedale 2',
              description: '[DA PERSONALIZZARE] Presidio ospedaliero e guardia medica',
              distance: '[DA PERSONALIZZARE] 7 km',
              phone: '[DA PERSONALIZZARE] +39 06 0000012',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20ospedale%202',
            },
          ],
        },
        {
          id: 'groceries',
          title: 'Supermercati',
          subtitle: 'Spesa nelle vicinanze',
          items: [
            {
              name: '[DA PERSONALIZZARE] Supermercato Centro',
              description: '[DA PERSONALIZZARE] Supermercato completo, aperto tutti i giorni.',
              distance: '[DA PERSONALIZZARE] 6 min a piedi',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20supermercato',
            },
            {
              name: '[DA PERSONALIZZARE] Alimentari Baiocco',
              description: '[DA PERSONALIZZARE] Piccolo negozio per acquisti rapidi e prodotti locali.',
              distance: '[DA PERSONALIZZARE] 3 min a piedi',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20alimentari',
            },
            {
              name: '[DA PERSONALIZZARE] Mercato rionale',
              description: '[DA PERSONALIZZARE] Frutta, verdura e prodotti freschi al mattino.',
              distance: '[DA PERSONALIZZARE] 10 min a piedi',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20mercato%20rionale',
            },
          ],
        },
        {
          id: 'checkout',
          title: 'Check-out',
          subtitle: 'Prima di partire',
          timeLabel: 'Orario',
          time: '[DA PERSONALIZZARE] entro le 10:00',
          tasksLabel: 'Un ultimo controllo',
          tasks: [
            '[DA PERSONALIZZARE] Spegnete luci e climatizzazione.',
            '[DA PERSONALIZZARE] Lasciate i piatti puliti.',
            '[DA PERSONALIZZARE] Chiudete porte e finestre.',
            '[DA PERSONALIZZARE] Lasciate le chiavi come concordato con l’host.',
          ],
          contactHost: 'Contatta l’host',
          review: 'Lascia una recensione',
        },
      ],
      emergency: {
        title: 'Emergenze',
        intro: 'Questi numeri sono mostrati solo come riferimento. Tocca Chiudi per tornare alla guida.',
        europeanLabel: 'Numero unico europeo',
        europeanNumber: '112',
        hostLabel: 'Telefono host',
        localLabel: 'Contatto locale',
      },
      recycling: {
        title: 'Raccolta differenziata',
        intro: 'Calendario settimanale dei ritiri sotto casa.',
        demoNote:
          'Programma dimostrativo: personalizzalo con i giorni reali prima della pubblicazione.',
        reminder: 'Attiva promemoria',
        reminderIntro: 'Scegli il calendario che usi sul telefono.',
        apple: 'Apple / iPhone',
        google: 'Google Calendar',
        addToGoogle: 'Aggiungi',
        noCollection: 'Nessun ritiro',
        calendarTitlePrefix: 'Raccolta',
        calendarDescription: 'Promemoria raccolta differenziata di LA MIA CASA.',
        calendarError: 'Calendario non disponibile: usa Google Calendar.',
        schedule: [
          { weekday: 1, day: 'Lunedì', material: 'Organico', kind: 'organic', collects: true },
          { weekday: 2, day: 'Martedì', material: 'Carta e cartone', kind: 'paper', collects: true },
          { weekday: 3, day: 'Mercoledì', material: 'Plastica e metalli', kind: 'plastic', collects: true },
          { weekday: 4, day: 'Giovedì', material: 'Organico', kind: 'organic', collects: true },
          { weekday: 5, day: 'Venerdì', material: 'Vetro', kind: 'glass', collects: true },
          { weekday: 6, day: 'Sabato', material: 'Indifferenziato', kind: 'general', collects: true },
          { weekday: 0, day: 'Domenica', material: 'Nessun ritiro', kind: 'none', collects: false },
        ],
      },
    },
    en: {
      languageCode: 'en',
      languageName: 'English',
      languageSelectorLabel: 'Language · Lingua',
      welcome:
        'Welcome. Everything you need to enjoy the home and the city is right here.',
      eyebrow: 'Your home, close at hand',
      guidePrompt: 'How can we help?',
      openSection: 'Open section',
      close: 'Close',
      maps: 'Open in Google Maps',
      copyPassword: 'Copy password',
      copyPasswordSuccess: 'Access copied',
      passwordCopied: 'Password copied',
      copyFailed: 'Copy failed: please select the password manually.',
      quickActionsLabel: 'Quick actions',
      quickActions: {
        whatsapp: 'WhatsApp host',
        recycling: 'Recycling',
        emergency: 'Emergencies',
      },
      sections: [
        {
          id: 'checkin',
          title: 'Check-in',
          subtitle: 'Arrival and access',
          addressLabel: 'Address',
          address: 'Via Tullio Ascarelli, 99 - Roma',
          checkInLabel: 'Check-in',
          checkIn: 'Remember to tell the Host what time you will arrive at the house.',
          housePhoto: '',
          housePhotoAlt: '[DA PERSONALIZZARE] LA MIA CASA exterior',
          housePhotoFallback: 'House photo coming soon',
          instructionsLabel: 'How to enter',
          instructions:
            'When you arrive, someone will welcome you and give you the house keys.',
        },
        {
          id: 'wifi',
          title: 'Wi-Fi',
          subtitle: 'Network and password',
          networkLabel: 'Network name',
          passwordLabel: 'Password',
          note: 'The network is available throughout the home.',
        },
        {
          id: 'rules',
          title: 'House rules',
          subtitle: 'The essentials',
          items: [
            { title: 'Climate', text: '[DA PERSONALIZZARE] The air-conditioning control is by the entrance.' },
            { title: 'Appliances', text: '[DA PERSONALIZZARE] Kitchen, oven, dishwasher and washing machine are available.' },
            { title: 'Recycling', text: '[DA PERSONALIZZARE] Bins are under the sink; the schedule is on the fridge.' },
            { title: 'Quiet hours', text: '[DA PERSONALIZZARE] Please keep noise down from 10:00 pm to 8:00 am.' },
            { title: 'House rules', text: '[DA PERSONALIZZARE] No smoking and no parties.' },
          ],
        },
        {
          id: 'food',
          title: 'Where to eat nearby',
          subtitle: 'Six places selected for you',
          places: [
            { name: '[DA PERSONALIZZARE] Trattoria del Vicolo', category: '[DA PERSONALIZZARE] Roman cuisine', tip: '[DA PERSONALIZZARE] Great for a relaxed dinner; try the dish of the day.', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Trattoria%20del%20Vicolo' },
            { name: '[DA PERSONALIZZARE] Forno della Piazza', category: '[DA PERSONALIZZARE] Bakery', tip: '[DA PERSONALIZZARE] Perfect for breakfast and pizza by the slice.', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Forno%20della%20Piazza' },
            { name: '[DA PERSONALIZZARE] L’Oliva', category: '[DA PERSONALIZZARE] Vegetarian', tip: '[DA PERSONALIZZARE] Seasonal dishes and good gluten-free options.', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20L%27Oliva' },
            { name: '[DA PERSONALIZZARE] Bottega 12', category: '[DA PERSONALIZZARE] Wine bar', tip: '[DA PERSONALIZZARE] A good choice for a quiet aperitivo.', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Bottega%2012' },
            { name: '[DA PERSONALIZZARE] Gelateria Fiore', category: '[DA PERSONALIZZARE] Gelateria', tip: '[DA PERSONALIZZARE] Artisan flavours and fresh fruit sorbets.', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Gelateria%20Fiore' },
            { name: '[DA PERSONALIZZARE] Terrazza Verde', category: '[DA PERSONALIZZARE] Panoramic restaurant', tip: '[DA PERSONALIZZARE] Reserve an outdoor table at sunset.', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20Terrazza%20Verde' },
          ],
        },
        {
          id: 'transport',
          title: 'Nearby transport',
          subtitle: 'Two routes outside the house',
          stopLabel: 'Stop outside the house',
          directionLabel: 'Direction',
          frequencyLabel: 'Frequency',
          moovit: 'Open in Moovit',
          lines: [
            {
              name: '[DA PERSONALIZZARE] Route 01',
              color: '#a94e34',
              stop: '[DA PERSONALIZZARE] Stop outside the house',
              direction: '[DA PERSONALIZZARE] Centre / Station',
              frequency: '[DA PERSONALIZZARE] every 15–20 min',
              stops: [
                '[DA PERSONALIZZARE] House',
                '[DA PERSONALIZZARE] Square',
                '[DA PERSONALIZZARE] Metro',
                '[DA PERSONALIZZARE] Centre',
              ],
              moovit: 'https://moovitapp.com/rome-61/lines/en',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20bus%20stop',
            },
            {
              name: '[DA PERSONALIZZARE] Route 02',
              color: '#65704a',
              stop: '[DA PERSONALIZZARE] Stop outside the house',
              direction: '[DA PERSONALIZZARE] University / Hospital',
              frequency: '[DA PERSONALIZZARE] every 20–25 min',
              stops: [
                '[DA PERSONALIZZARE] House',
                '[DA PERSONALIZZARE] Park',
                '[DA PERSONALIZZARE] University',
                '[DA PERSONALIZZARE] Hospital',
              ],
              moovit: 'https://moovitapp.com/rome-61/lines/en',
              map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20bus%20stop',
            },
          ],
        },
        {
          id: 'health',
          title: 'Pharmacies & hospitals',
          subtitle: 'Nearby healthcare',
          pharmaciesTab: 'Pharmacies',
          hospitalsTab: 'Hospitals',
          tabsLabel: 'Choose the type of healthcare',
          openPharmacies: 'Find open pharmacies',
          emergencyRooms: 'Find an emergency room in Lazio',
          emergencyNote:
            'Call 112 in an emergency: do not choose a hospital based only on distance.',
          phoneLabel: 'Phone',
          pharmacies: [
            { name: '[DA PERSONALIZZARE] Pharmacy 1', description: '[DA PERSONALIZZARE] Address and directions', distance: '[DA PERSONALIZZARE] 3 min walk', phone: '[DA PERSONALIZZARE] +39 06 0000001', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20pharmacy%201' },
            { name: '[DA PERSONALIZZARE] Pharmacy 2', description: '[DA PERSONALIZZARE] Address and directions', distance: '[DA PERSONALIZZARE] 7 min walk', phone: '[DA PERSONALIZZARE] +39 06 0000002', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20pharmacy%202' },
            { name: '[DA PERSONALIZZARE] Pharmacy 3', description: '[DA PERSONALIZZARE] Address and directions', distance: '[DA PERSONALIZZARE] 10 min walk', phone: '[DA PERSONALIZZARE] +39 06 0000003', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20pharmacy%203' },
          ],
          hospitals: [
            { name: '[DA PERSONALIZZARE] Hospital 1', description: '[DA PERSONALIZZARE] Emergency room and main services', distance: '[DA PERSONALIZZARE] 4 km', phone: '[DA PERSONALIZZARE] +39 06 0000011', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20hospital%201' },
            { name: '[DA PERSONALIZZARE] Hospital 2', description: '[DA PERSONALIZZARE] Hospital and out-of-hours medical service', distance: '[DA PERSONALIZZARE] 7 km', phone: '[DA PERSONALIZZARE] +39 06 0000012', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20hospital%202' },
          ],
        },
        {
          id: 'groceries',
          title: 'Supermarkets',
          subtitle: 'Groceries nearby',
          items: [
            { name: '[DA PERSONALIZZARE] Central Supermarket', description: '[DA PERSONALIZZARE] Full supermarket, open every day.', distance: '[DA PERSONALIZZARE] 6 min walk', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20supermercato' },
            { name: '[DA PERSONALIZZARE] Baiocco Grocery', description: '[DA PERSONALIZZARE] Small shop for quick purchases and local products.', distance: '[DA PERSONALIZZARE] 3 min walk', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20alimentari' },
            { name: '[DA PERSONALIZZARE] Local Market', description: '[DA PERSONALIZZARE] Fruit, vegetables and fresh products in the morning.', distance: '[DA PERSONALIZZARE] 10 min walk', map: 'https://www.google.com/maps/search/?api=1&query=%5BDA%20PERSONALIZZARE%5D%20mercato%20rionale' },
          ],
        },
        {
          id: 'checkout',
          title: 'Check-out',
          subtitle: 'Before you leave',
          timeLabel: 'Time',
          time: '[DA PERSONALIZZARE] by 10:00 am',
          tasksLabel: 'One last check',
          tasks: [
            '[DA PERSONALIZZARE] Turn off lights and climate control.',
            '[DA PERSONALIZZARE] Leave the dishes clean.',
            '[DA PERSONALIZZARE] Close doors and windows.',
            '[DA PERSONALIZZARE] Leave the keys as agreed with the host.',
          ],
          contactHost: 'Contact the host',
          review: 'Leave a review',
        },
      ],
      emergency: {
        title: 'Emergencies',
        intro: 'These numbers are shown for reference only. Tap Close to return to the guide.',
        europeanLabel: 'European emergency number',
        europeanNumber: '112',
        hostLabel: 'Host phone',
        localLabel: 'Local contact',
      },
      recycling: {
        title: 'Recycling collection',
        intro: 'Weekly collection schedule outside the house.',
        demoNote:
          'Demo schedule: replace it with the real collection days before publishing.',
        reminder: 'Set reminders',
        reminderIntro: 'Choose the calendar you use on your phone.',
        apple: 'Apple / iPhone',
        google: 'Google Calendar',
        addToGoogle: 'Add',
        noCollection: 'No collection',
        calendarTitlePrefix: 'Collection',
        calendarDescription: 'LA MIA CASA recycling collection reminder.',
        calendarError: 'Calendar unavailable: use Google Calendar.',
        schedule: [
          { weekday: 1, day: 'Monday', material: 'Food waste', kind: 'organic', collects: true },
          { weekday: 2, day: 'Tuesday', material: 'Paper and cardboard', kind: 'paper', collects: true },
          { weekday: 3, day: 'Wednesday', material: 'Plastic and metal', kind: 'plastic', collects: true },
          { weekday: 4, day: 'Thursday', material: 'Food waste', kind: 'organic', collects: true },
          { weekday: 5, day: 'Friday', material: 'Glass', kind: 'glass', collects: true },
          { weekday: 6, day: 'Saturday', material: 'General waste', kind: 'general', collects: true },
          { weekday: 0, day: 'Sunday', material: 'No collection', kind: 'none', collects: false },
        ],
      },
    },
  },
};

export function getLocalizedContent(language) {
  const selected = content.locale[language] ?? content.locale.it;

  return {
    ...selected,
    brand: content.brand,
    contacts: content.contacts,
    links: content.links,
    healthLinks: content.healthLinks,
    wifi: content.wifi,
  };
}
